### ISSUE TITLE
How to judge the direction is up or down when scrolling?

### ISSUE THREAD

**Issue by Muran-Hu** [eberhara/react-bidirectional-infinite-scroll#10]
Two question:
1. How to judge the direction is up or down when scrolling?
2. How to judge which key is clicked, up or down?

**Comment by eberhara** [comment]
@Muran-Hu the direction of the scroll is now being handled by the callbacks `onScrollUp` `onScrollDown` `onScrollLeft` `onScrollRight` added on #12 

Thanks!

**Comment by eberhara** [comment]
@Muran-Hu As of version 2 (released today), the `onScroll` callback receives two parameters:
```jsx
handleScroll = (position, previousPosition) => {
  const diffScroll = position - previousPosition
  const direction = diffScroll > 0
    ? 'down'
    : 'up'

  console.log(`Scroll ${direction} to ${position}`)
}
```

So now you can calculate the horizontal or vertical direction based on position and previous position.
