### ISSUE TITLE
Expected version "^9.2.0 || ^8.0.0"

### ISSUE THREAD

**Issue by miladezzat** [eberhara/react-bidirectional-infinite-scroll#21]
```bash
error react-bidirectional-infinite-scroll@2.0.1: The engine "node" is incompatible with this module. Expected version "^9.2.0 || ^8.0.0". Got "16.14.2"
error Found incompatible module.
```

**Comment by miladezzat** [comment]
@eberhara

**Comment by mira-thakkar** [comment]
@miladezzat how did you fix this issue ?

**Comment by miladezzat** [comment]
> @miladezzat how did you fix this issue ?

yes it fixed on the last version, upgrade your version

**Comment by mira-thakkar** [comment]
i suppose latest version is in master branch, and [package.json](https://github.com/eberhara/react-bidirectional-infinite-scroll/blob/0f67843c42a36ecc96ffe1c8561928bf3c4a39f2/package.json#L69) in master branch still says to have node at `"^9.2.0 || ^8.0.0"` version, it would be helpful if you can say how you upgraded the version!

**Comment by eberhara** [comment]
Hi, I plan to get back to this project and update it in the next weeks. But if someone can open a pull request updating it, I can review and merge it.
