### ISSUE TITLE
update react and add proptypes as dependency

### ISSUE THREAD

**Issue by phoebeschmidt** [eberhara/react-bidirectional-infinite-scroll#9]
since React 15.5 PropTypes has been moved into its own library. 
https://reactjs.org/docs/typechecking-with-proptypes.html

I'm trying to use this plugin with React v.16.0 and it's incompatible.

**Comment by alexandraclaire** [comment]
I am also having this problem - it would be good to get a fix because it's a great idea.

**Comment by eberhara** [comment]
Hey @phoebeschmidt @alexandraclaire 

I am planning to fix this as parte of v2. There is a branch where I am working on it.

**Comment by eberhara** [comment]
@alexandraclaire @phoebeschmidt v2 is on!
Now it supports both react 15 and 16.

Thank you!
